name: "pack"
author: "敖律风"
description: "打包 hbuilderX 项目"
inputs:
  username:
    description: "hbuilderX 账号"
    required: true
  password:
    description: "hbuilderX 密码"
    required: true
runs:
  using: 'node22'
  pre: script/init.js
  main: script/pack.js
  post: script/clean.js